os: linux
language: node_js
node_js:
  - "14"
  - "12"
  - "10"
env:
  - NPM_SCRIPT=test
matrix:
  fast_finish: true
  include:
    - os: windows
      # On Windows, test only the last LTS.
      node_js: "10"
      # On Windows, run test:main only instead of test.
      # https://github.com/qunitjs/qunit/issues/1359
      env: NPM_SCRIPT=test:main
    - os: osx
      # On Mac, test only the last LTS.
      node_js: "10"
    - os: linux
      node_js: "10"
      env: NPM_SCRIPT=coveralls
    - stage: "Update search index"
      # https://docs.travis-ci.com/user/conditions-v1
      if: (branch = master) AND (type IN (push, cron))
      language: ruby
      rvm: 2.7
      cache: bundler
      before_install: cd docs/
      install: bundle install
      script: bundle exec jekyll algolia
script:
  - npm run $NPM_SCRIPT
cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache
    - node_modules
